-- CreateEnum
CREATE TYPE "Poste" AS ENUM ('PRESIDENT', 'PRESIDENTE', 'VICE_PRESIDENT', 'VICE_PRESIDENTE', 'TRESORIER', 'TRESORIERE', 'SECRETAIRE', 'JOUEUR', 'VISITEUR');

-- AlterTable
ALTER TABLE "User" ADD COLUMN     "poste" "Poste" NOT NULL DEFAULT 'VISITEUR';
